name: Automated Robot Framework Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  robot_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Python
        run: |
          curl -LO "https://github.com/actions/python-versions/releases/download/3.10.0-117927/python-3.10.0-linux-18.04-x64.tar.gz"
          tar -xf python-3.10.0-linux-18.04-x64.tar.gz -C $RUNNER_TOOL_CACHE
          export PATH="$RUNNER_TOOL_CACHE/python/3.10.0/x64:$PATH"
        if: runner.os == 'Linux' && startsWith(runner.tool_cache_dir, '/opt/hostedtoolcache/Python/')

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH=$HOME/.local/bin:$PATH
        if: runner.os == 'Linux' && startsWith(runner.tool_cache_dir, '/opt/hostedtoolcache/Python/')

      - name: Install Robot Framework
        run: |
          pip install --upgrade robotframework
        if: runner.os == 'Linux' && startsWith(runner.tool_cache_dir, '/opt/hostedtoolcache/Python/')

      - name: Install Streamlit
        run: |
          pip install streamlit
        if: runner.os == 'Linux' && startsWith(runner.tool_cache_dir, '/opt/hostedtoolcache/Python/')

      - name: Install Chrome WebDriver
        run: |
          CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}')
          LATEST_CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          curl -o /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip /tmp/chromedriver.zip -d /tmp
          sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
        if: runner.os == 'Linux' && startsWith(runner.tool_cache_dir, '/opt/hostedtoolcache/Python/')

      - name: Set up Poetry Shell and Run Commands
        run: |
          poetry shell && poetry install && streamlit run app.py && robot tests/Test1.py
        working-directory: ${{ github.workspace }}

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: robot-test-results
          path: .
