name: Automated E2E test

on:
  push:
  # branches: ["main"]
  pull_request:
  # branches: ["main"]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  envfile: ${{ secrets.ENV }}
  mode: testing
  "POETRY_VIRTUALENVS_IN_PROJECT": false
  "POETRY_VIRTUALENVS_OPTIONS_ALWAYS_COPY": true
  "POETRY_VIRTUALENVS_OPTIONS_NO_PIP": false
  "POETRY_VIRTUALENVS_OPTIONS_NO_SETUPTOOLS": false

jobs:
  robot:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.10" ] #TODO:, "3.11"]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python ${{ matrix.python-version }} on ${{matrix.os}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
          cache-dependency-path: |
            **/setup.cfg
            **/requirements*.txt
            poetry.lock
            pyproject.toml

      - name: Write environment
        run: |
          echo $envfile > .env
          sed -i 's/ /\n/g' .env
          source .env

      - name: Install dependencies
        run: |
          #make install
          #make install-tests
          # poetry config settings.virtualenvs.create false --local
          poetry install --no-root
          source $(poetry env info --path)/bin/activate

      - name: Streamlit run
        run: |
          make run &
          sleep 10

      - name: Robot Framework
        continue-on-error: true
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          browser: "chrome" #firefox
          robot_threads: 2
          robot_tests_dir: "tests"
          robot_reports_dir: "tests/reports"
          allowed_shared_memory: "1g"
          # robot_runner_image: "ppodgorsek/robot-framework:latest"

      - uses: vimtor/action-zip@v1.1
        with:
          files: tests/reports
          recursive: true
          dest: test-reports.zip

      - uses: actions/upload-artifact@v3
        with:
          name: test-reports-zip
          path: ${{ github.workspace }}/test-reports.zip

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: tests
          path: |
            tests
          retention-days: 90

# https://github.com/actions/setup-python/blob/v4/docs/advanced-usage.md#caching-packages
# doc: poetry-config https://python-poetry.org/docs/configuration/
