name: Automated Robot Framework Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  robot_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        run: echo "::group::Checkout"
        shell: bash
        env:
          data: Checkout
        command: |
          echo "::workflow-command parameter1={data}::{data}"
          # Actual checkout command here
          git checkout main
        continue-on-error: true

      - name: Download Python
        run: echo "::group::Download Python"
        shell: bash
        env:
          data: Download Python
        command: |
          echo "::workflow-command parameter1={data}::{data}"
          curl -LO "https://github.com/actions/python-versions/releases/download/3.10.0-117927/python-3.10.0-linux-18.04-x64.tar.gz"
          tar -xf python-3.10.0-linux-18.04-x64.tar.gz -C $RUNNER_TOOL_CACHE
          export PATH="$RUNNER_TOOL_CACHE/python/3.10.0/x64:$PATH"
        continue-on-error: true
        if: runner.os == 'Linux' && startsWith(runner.tool_cache_dir, '/opt/hostedtoolcache/Python/')

      - name: Install Poetry
        run: echo "::group::Install Poetry"
        shell: bash
        env:
          data: Install Poetry
        command: |
          echo "::workflow-command parameter1={data}::{data}"
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH=$HOME/.local/bin:$PATH
        continue-on-error: true
        if: runner.os == 'Linux' && startsWith(runner.tool_cache_dir, '/opt/hostedtoolcache/Python/')

      - name: Set up Poetry Virtual Environment
        run: echo "::group::Set up Poetry Virtual Environment"
        shell: bash
        env:
          data: Set up Poetry Virtual Environment
        command: |
          echo "::workflow-command parameter1={data}::{data}"
          poetry install
        continue-on-error: true
        working-directory: ${{ github.workspace }}

      - name: Run Poetry Shell and Robot Framework Tests
        run: echo "::group::Run Poetry Shell and Robot Framework Tests"
        shell: bash
        env:
          data: Run Poetry Shell and Robot Framework Tests
        command: |
          echo "::workflow-command parameter1={data}::{data}"
          poetry shell
          poetry run robot tests/Test1.py
        continue-on-error: true
        working-directory: ${{ github.workspace }}

      - name: Upload Test Results
        run: echo "::group::Upload Test Results"
        shell: bash
        env:
          data: Upload Test Results
        command: |
          echo "::workflow-command parameter1={data}::{data}"
          # Upload test results command here
        continue-on-error: true
        with:
          name: robot-test-results
          path: .
